logic:
  build: ./config/docker/logic
  expose:
    - "4567"
  volumes:
    - ./logic:/app
  working_dir: /app
  command: python logic.py
  environment:
    - CHARGER_URL=http://charger:6082
    - FILLER_URL=http://filler:4568
  links:
    - filler
    - charger
filler:
  image: ruby
  expose:
    - "4568"
  volumes:
    - ./filler:/app
  working_dir: /app
  environment:
    - PORT=4568
    - LOGIC_PORT=4567
  entrypoint: /app/entrypoint.sh
charger:
  build: ./config/docker/charger
  expose:
    - "6082"
  volumes:
    - ./charger:/app
  working_dir: /app
  command: python payment_svc.py
interface:
  build: ./config/docker/interface
  environment:
    - LOGIC_URL=http://logic:4567
    - CHARGER_URL=http://charger:6082
    - FILLER_URL=http://filler:4568
    - PORT=8080
  expose:
    - "8080"
  ports:
    - 8080:8080
  volumes:
    - ./interface:/app
  working_dir: /app
  entrypoint: /root/entrypoint.sh
  links:
    - logic
