logic:
  build: ./config/docker/logic
  expose:
    - "4567"
  ports:
    - 8081:4567
  volumes:
    - ./logic:/app
  working_dir: /app
  command: python logic.py
  links:
    - filler
filler:
  build: ./config/docker/logic
  expose:
    - "4568"
  volumes:
    - ./logic:/app
  working_dir: /app
  command: python filler.py
interface:
  build: ./config/docker/interface
  environment:
    - LOGIC_URL=http://logic:4567
    - PORT=8080
  expose:
    - "8080"
  ports:
    - 8080:8080
  volumes:
    - ./interface:/app
  working_dir: /app
  entrypoint: /root/entrypoint.sh
  links:
    - logic
