version: '2'
services:
  logic:
    build: ./logic
    depends_on:
      - filler
      - charger
    networks:
      - frontend
      - backend

  filler:
    build: ./filler
    networks:
      - backend

  charger:
    build: ./charger
    networks:
      - backend

  interface:
    build: ./interface
    ports:
      - 8080:8080
    depends_on:
      - logic
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
